- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/local/mnt/data/mail/sent
  usual: true
  archived: true
  sync_back: true
  id: 1
  labels: ["sent"]
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/local/mnt/data/mail/inbox
  usual: true
  archived: false
  sync_back: true
  id: 2
  labels: []
