#
# Workflow to validate that dotfiles are setup correct for all supported platforms
#

name: Validate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  init:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - platform: ubuntu-latest
            launch: bash init.sh
          - platform: macos-latest
            launch: bash init.sh
          - platform: windows-latest
            launch: cmd /c init.bat

    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Runs a single command using the runners shell
      - name: Initialize environment
        working-directory: ${{ github.workspace }}
        run: ${{ matrix.launch }} -c -y

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Inject GitHub slug variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dotfiles
          # Generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: source/docker/Dockerfile.ubuntu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  msys2:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Initialize environment
        run: |
          echo 'Running 'Mycelio' environment setup in MSYS2!'
          pwd
          rm -rf "$HOME/dotfiles"
          cp --dereference -af $(cygpath "$GITHUB_WORKSPACE/") "$HOME/dots/"
          cd "$HOME"
          pwd
          ./dots/init.sh --clean --force
